### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'stopListening'

### ISSUE THREAD

**Issue by allenap** [shylent/python-tx-tftp#30]
```console
$ twistd3 --nodaemon --pidfile= tftp --enable-reading --root-directory=$PWD
...
2017-04-05T14:44:50+0200 [-] RemoteOriginReadSession starting on 37066
2017-04-05T14:44:50+0200 [-] Starting protocol <tftp.bootstrap.RemoteOriginReadSession object at 0x7f06256ee5c0>
2017-04-05T14:44:55+0200 [RemoteOriginReadSession (UDP)] (UDP Port 37066 Closed)
2017-04-05T14:44:55+0200 [RemoteOriginReadSession (UDP)] Stopping protocol <tftp.bootstrap.RemoteOriginReadSession object at 0x7f06256ee5c0>
2017-04-05T14:44:56+0200 [-] Timed during option negotiation process
2017-04-05T14:44:56+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 395, in startReactor
            self.config, oldstdout, oldstderr, self.profiler, reactor)
          File "/usr/lib/python3/dist-packages/twisted/application/app.py", line 310, in runReactorWithLogging
            reactor.run()
          File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1195, in run
            self.mainLoop()
          File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1204, in mainLoop
            self.runUntilCurrent()
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/usr/lib/python3/dist-packages/tftp/bootstrap.py", line 207, in timedOut
            self.cancel()
          File "/usr/lib/python3/dist-packages/tftp/bootstrap.py", line 202, in cancel
            self.transport.stopListening()
        builtins.AttributeError: 'NoneType' object has no attribute 'stopListening'
```

To recreate it's very similar to the previous example:

```python
import socket, time
from tftp.datagram import RRQDatagram

# Create datagram requesting read of an existing file. At least one
# option MUST be defined.
dg = RRQDatagram(b"something.txt", b"octet", {b"tsize": b"0"})

# Create a new DGRAM socket and send this packet to the running tftp
# daemon, then immediately close the socket.
s = socket.socket(type=socket.SOCK_DGRAM)
s.sendto(dg.to_wire(), 0, ("127.0.0.1", 1069))
# Now sleep for a while. Less than ~1 and the previous (Port/socket)
# error will occur. More than ~4 and no error will occur.
time.sleep(3.5)
s.close()
```

**Comment by allenap** [comment]
Fixed by #31.
